name: dev

on:
  push:
    branches:
      - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: my-image
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=v
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          namespace: my-okteto-namespace
      - name: "Trigger the pipeline"
        uses: okteto/pipeline@latest
        with:
          name: my-app
          namespace: my-okteto-namespace
          timeout: 8m
